<a href="https://colab.research.google.com/github/ishancoderr/scenic-route-finder/blob/main/Scenic_root_finder_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#
import numpy as np

height, width = 4, 4
num = [0, 0, 2, 3, 0, 5, 0, 7, 0, 9, 10, 0, 0, 0, 0, 0]
map= np.array(num).reshape((height, width))
print(map)

[[ 0  0  2  3]
 [ 0  5  0  7]
 [ 0  9 10  0]
 [ 0  0  0  0]]


In [43]:
import sys
Value = 0

for i in range(len(map)):
  for j in range(len(map)):
    print(f"{map[i,j]}")
    if map[i,j]==0:
      print(f"{map[i+1,j+1]+map[i,j+1]+map[i+1,j]+map[i-1,j-1]+map[i-1,j]}")
      #sys.exit()
      
  
    



0
5
0
7
2
3
0
17
5
0
19
7
0
16
9
10
0


IndexError: ignored